CREATE TABLE Actor(Name VARCHAR(40), Movie VARCHAR(80), Year INTEGER, Role VARCHAR(40))ENGINE = INNODB;

LOAD DATA LOCAL INFILE '~/data/actors.csv' INTO TABLE Actor
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';